# 1. admin has to create PersistentVolume named e.g. "pv-o3as", see storage.pvName below
#    example to create NFS PV is in the file pv-o3as-nfs.yml
#    NB! NFS has to be installed and configured!
# 2. while creating the app, specify the namespace 
#    (create, if necessary, e.g. by adding --create-namespace or ask your k8s admin):
# helm install o3as-app o3as-app --namespace o3as --values o3as-app/values-prod.yaml

# name of the master node
k8smaster: kubeserver.localdomain

# name of the issuer, used in ingress
issuers:
  letsencrypt: letsencrypt-prod

# info needed to obtain letsencrypt certificate
# (!!) Careful with the rate limits of letsencrypt (!!)
letsencrypt:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: some.email@real.world

# site-names used for the API and WebApp
sites:
  hostApi: api.o3as.fedcloud.eu
  hostWeb: web.o3as.fedcloud.eu

# global environment settings
env:
  o3asLogLevel: "INFO"
  o3asDataPath: /data/Skimmed
  o3asDataSourcesCsv: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/Data sources - Sources.csv"
#  o3asPublishedListRemote: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/o3as_published_data.txt"
  o3asPublishedListRemote: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/e35e8687240c75aeb566866418578f97835db401/o3as_published_data.txt"
  hdf5UseFileLocking: "TRUE" 

# properties of storage for skimmed data
storage:
  volumeName: o3as-storage
  pvcName: o3as-pvc
  pvcStorageClassName: '""'
  pvcAccessMode: ReadWriteMany
  pvcStorage: 3Gi
  pvName: pv-o3as

# UID and GID to run containers
security:
  runAsUser: 1000
  runsAsGroup: 1000

# properties of individual containers
o3api:
  image: o3as/o3api
  imageTag: "0.8.4"
  imagePullPolicy: "Always"
  deployReplicas: 2

o3web:
  image: o3as/o3webapp
  imageTag: "1.0"
  imagePullPolicy: "Always"
  deployReplicas: 1

nsupdate:
  image: o3as/nsupdate
  imageTag: "1.0"
  imagePullPolicy: "Always"

rclone:
  image: rclone/rclone
  imageTag: "1.58"
  runCronRclone: "False"

getPublished:
  image: alpine
  imageTag: "3.14"
  imagePullPolicy: "Always"
  command: "https://git.scc.kit.edu/synergy.o3as/o3k8s/-/raw/main/scripts/get-published-data.sh"
