# 1. admin has to create PersistentVolume named e.g. "pv-o3as", see storage.pvName below
#    example to create NFS PV is in the file pv-o3as-nfs.yml
#    NB! NFS has to be installed and configured!
# 2. while creating the app, specify the namespace 
#    (create, if necessary, e.g. by adding --create-namespace or ask your k8s admin):
# helm install o3as-app o3as-app --namespace o3as --values o3as-app/values-test.yaml

# hostname of the master node
k8smaster: kubeserver.localdomain

# master node role
k8smasterNodeRole: "node-role.kubernetes.io/control-plane"

# name of the issuer, used in ingress
issuers:
  letsencrypt: letsencrypt-site

# info needed to obtain letsencrypt certificate
# in test deployment we use "acme-staging" to avoid rate limits of letsencrypt
letsencrypt:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: some.real@email.world

sites:
  hostApi: o3api.test.fedcloud.eu
  hostWeb: o3web.test.fedcloud.eu
  
env:
  o3asLogLevel: "DEBUG"
  o3asDataPath: /data/Skimmed
  o3asDataSourcesCsv: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/Data sources - Sources.csv"
  o3asPublishedListRemote: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/test/o3as_published_data.txt"
#  o3asPublishedListRemote: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/e35e8687240c75aeb566866418578f97835db401/o3as_published_data.txt"
  # need boolean here
  hdf5UseFileLocking: false

storage:
  volumeName: o3as-storage
  pvcName: o3as-pvc
  pvcStorageClassName: '""'
  pvcAccessMode: ReadWriteMany
  pvcStorage: 3Gi
  pvName: pv-o3as

security:
  runAsUser: "1000"
  runAsGroup: "1000"
  fsGroup: "1000"

o3api:
  image: o3as/o3api
  imageTag: "test"
  imagePullPolicy: "Always"
  deployReplicas: "1"

o3web:
  image: o3as/o3webapp
  imageTag: "test"
  imagePullPolicy: "Always"
  deployReplicas: "1"
  nextPublicApiHost: "https://o3api.test.fedcloud.eu/api/v1"

nsupdate:
  image: o3as/nsupdate
  imageTag: "1.0"
  imagePullPolicy: "Always"

rclone:
  image: rclone/rclone
  imageTag: "1.58"
  runCronRclone: "False"

getPublished:
  image: alpine
  imageTag: "3.14"
  imagePullPolicy: "Always"
  command: "https://git.scc.kit.edu/synergy.o3as/o3k8s/-/raw/main/scripts/get-published-data.sh"
