# while creating the app, specify the same namespace:
# helm install o3as-app-helm o3as-app-helm --create-namespace --namespace o3as --values o3as-app-helm/values-test.yaml

issuers:
  letsencrypt: letsencrypt-prod

# info needed to obtain letsencrypt certificate
# (!!) Careful with the rate limits of letsencrypt (!!)
letsencrypt:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: some.email@real.world

sites:
  hostApi: api.o3as.fedcloud.eu
  hostWeb: web.o3as.fedcloud.eu
  
env:
  o3asLogLevel: "INFO"
  o3asDataPath: /data/Skimmed
  o3asDataSourcesCsv: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/Data sources - Sources.csv"
  o3asPublishedListRemote: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/o3as_published_data.txt"
  hdf5UseFileLocking: "TRUE"

commands:
  getPublishedData: "https://git.scc.kit.edu/synergy.o3as/o3k8s/-/raw/main/scripts/get-published-data.sh"
  
pv:
  nfs:
    name: nfs-o3as-data
    path: /pv/o3as-data
    server: kubeserver
    
security:
  runAsUser: 1000
  runsAsGroup: 1000

o3api:
  image: o3as/o3api
  imageTag: "0.8.4"
  imagePullPolicy: "Always"
  deployReplicas: 2

o3web:
  image: o3as/o3webapp
  imageTag: "1.0"
  imagePullPolicy: "Always"
  deployReplicas: 1

nsupdate:
  image: o3as/nsupdate
  imageTag: "1.0"
  imagePullPolicy: "Always"

rclone:
  image: rclone/rclone
  imageTag: "1.58"
  runCronRclone: "False"

getPublished:
  image: alpine
  imageTag: "3.14"
  imagePullPolicy: "Always"

