apiVersion: batch/v1
kind: CronJob
metadata:
  name: o3as-nsupdate
spec:
  schedule: "0 1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nsupdate
              image: o3as/nsupdate:v1.0
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                  name: o3as-config
                - secretRef:
                  name: o3as-secrets
          restartPolicy: Never
          nodeSelector:
             kubernetes.io/hostname: kubeserver.localdomain