apiVersion: batch/v1
kind: CronJob
metadata:
  name: o3as-rclone
  namespace: o3as
spec:
  schedule: "5 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: rclone
              image: rclone/rclone:1.58
              args:
              - "--webdav-user"
              - $(RSTORAGE_USER)
              - "--webdav-pass"
              - $(RSTORAGE_PASS)
              - "sync"
              - "--webdav-url"
              - $(RSTORAGE_URL)
              - "--webdav-headers"
              - "X-Requested-With,XMLHttpRequest"
              - ":webdav:"
              - /data
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: o3as-config
                - secretRef:
                    name: o3as-secrets
              volumeMounts:
              - mountPath: /data
                name: nfs-o3as-data
          volumes:
          - name: nfs-o3as-data
            nfs:
              path: /pv/o3as-data
              server: kubeserver
          restartPolicy: Never
