apiVersion: batch/v1
kind: CronJob
metadata:
  name: o3as-rclone
  namespace: o3as
spec:
  schedule: "5 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: rclone
              image: rclone/rclone:1.58
              args: 
              - "--webdav-user"
              - $(RSTORAGE_USER)
              - "--webdav-pass"
              - $(RSTORAGE_PASS)
              - "sync"
              - "--webdav-url"
              - $(RSTORAGE_URL)
              - "--webdav-headers"
              - "X-Requested-With,XMLHttpRequest"
              - ":webdav:"
              - "$(O3AS_DATA_PATH_HOST)"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: o3as-config
                - secretRef:
                    name: o3as-secrets
          restartPolicy: Never
