apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-o3as
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/pv/o3as-data"