apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-o3as
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: kubeserver.localdomain
    path: "/pv/o3as-data"
  mountOptions:
    - nfsvers=4
