apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: o3as-ingress
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: {{.Values.issuers.letsencrypt}}
    nginx.ingress.kubernetes.io/secure-backends: 'true'
#    nginx.ingress.kubernetes.io/cors-allow-methods: GET, PUT, POST, OPTIONS
#    nginx.ingress.kubernetes.io/cors-allow-origin: http(s)://test.o3as.fedcloud.eu, http(s)://web.o3as.fedcloud.eu
#    nginx.ingress.kubernetes.io/enable-cors: 'true'
#    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
##    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
##    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'

spec:
  tls:
  - hosts:
    - {{.Values.sites.hostApi}}
    - {{.Values.sites.hostWeb}}
    secretName: {{.Values.sites.hostWeb}}

  rules:
  - host: {{.Values.sites.hostWeb}}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          serviceName: o3api-service
          servicePort: 5005
      - path: /
        pathType: Prefix
        backend:
          serviceName: o3web-service
          servicePort: 3000
  - host: {{.Values.sites.hostApi}}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          serviceName: o3api-service
          servicePort: 5005
      - path: /
        pathType: Exact
        backend:
          serviceName: o3api-service
          servicePort: 5005
