apiVersion: batch/v1
kind: Job
metadata:
  name: o3as-job-get-published-data
  namespace: {{.Values.namespace}}
spec:
  template:
    spec:
      securityContext:
        runAsUser: {{.Values.security.runAsUser}}
        runAsGroup: {{.Values.security.runAsGroup}}
      containers:
        - name: get-published-data
          image: {{.Values.images.repositoryGetPub}}:{{.Values.images.tagGetPub}}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: o3as-config
          env:
          - name: O3AS_DATA_PATH
            value: {{.Values.env.o3asDataPath}}
          command: ["/bin/sh"]
          args: ["-c", "wget -O - https://git.scc.kit.edu/synergy.o3as/o3k8s/-/raw/main/scripts/get-published-data.sh | sh"]
          volumeMounts:
            - mountPath: /data
              name: {{.Values.pv.nfs.name}}
      volumes:
      - name: {{.Values.pv.nfs.name}}
        nfs:
          path: {{.Values.pv.nfs.path}}
          server: {{.Values.pv.nfs.server}}
      restartPolicy: Never
