apiVersion: batch/v1
kind: Job
metadata:
  name: o3as-job-nsupdate
  namespace: o3as
spec:
  template:
    spec:
      containers:
        - name: nsupdate
          image: o3as/nsupdate:1.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: o3as-config
            - secretRef:
                name: o3as-secrets
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: kubeserver.localdomain
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"