namespace: o3as

cronApiVersion: batch/v1

letsencrypt:
  acme:
    email: some.email@real.world

sites:
  hostApi: api.o3as.fedcloud.eu
  hostWeb: web.o3as.fedcloud.eu
  
env:
  o3asDataPath: /data/Skimmed
  o3asDataSourcesCsv: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/Data sources - Sources.csv"
  o3asPublishedListRemote: "https://git.scc.kit.edu/synergy.o3as/o3sources/-/raw/main/o3as_published_data.txt"
  hdf5UseFileLocking: "TRUE"

commands:
  getPublishedData: "https://git.scc.kit.edu/synergy.o3as/o3k8s/-/raw/helm/scripts/get-published-data.sh"
  
pv:
  nfs:
    name: nfs-o3as-data
    path: /pv/o3as-data
    server: kubeserver
    
security:
  runAsUser: 1000
  runsAsGroup: 1000

images:
  repositoryApi: o3as/o3api
  tagApi: 0.8.2
  repositoryWeb: o3as/o3webapp
  tagWeb: 1.0
  repositoryNsupdate: o3as/nsupdate
  tagNsupdate: 1.0
  repositoryRclone: rclone/rclone
  tagRclone: 1.58
  repositoryGetPub: alpine
  tagGetPub: 3.14
