letsencrypt:
  acme:
    email: some.email@real.world

sites:
  hostApi: o3api.test.fedcloud.eu
  hostWeb: o3web.test.fedcloud.eu

deployment:
  image:
    repositoryApi: o3as/o3api
    tagApi: test
    repositoryWeb: o3as/o3webapp
    tagWeb: 1.0
    repositoryNsupdate: o3as/nsupdate
    tagNsupdate: 1.0
