apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{.Values.issuers.letsencrypt}}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{.Values.letsencrypt.acme.server}}
    email: {{.Values.letsencrypt.acme.email}}
    privateKeySecretRef:
      name: {{.Values.issuers.letsencrypt}}
    solvers:
    - http01:
        ingress:
          class: nginx
