apiVersion: batch/v1
kind: Job
metadata:
  name: o3as-job-nsupdate
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: nsupdate
          image: {{.Values.nsupdate.image}}:{{.Values.nsupdate.imageTag}}
          imagePullPolicy: {{.Values.nsupdate.imagePullPolicy}}
          envFrom:
            - configMapRef:
                name: o3as-config
            - secretRef:
                name: o3as-secrets
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: {{.Values.k8smaster}}
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
