apiVersion: batch/v1
kind: Job
metadata:
  name: o3as-job-get-published-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  template:
    spec:
      securityContext:
        runAsUser: {{.Values.security.runAsUser}}
        runAsGroup: {{.Values.security.runAsGroup}}
      containers:
        - name: get-published-data
          image: {{.Values.getPublished.image}}:{{.Values.getPublished.imageTag}}
          imagePullPolicy: {{.Values.getPublished.imagePullPolicy}}
          envFrom:
            - configMapRef:
                name: o3as-config
          env:
          - name: O3AS_DATA_SOURCES_CSV
            value: {{.Values.env.o3asDataSourcesCsv}}
          - name: O3AS_PUBLISHED_LIST_REMOTE
            value: {{.Values.env.o3asPublishedListRemote}}
          command: ["/bin/sh"]
          args: ["-c", "wget -O - {{.Values.getPublished.command}} | sh"]
          volumeMounts:
            - mountPath: /data
              name: {{.Values.storage.volumeName}}
      volumes:
      - name: {{.Values.storage.volumeName}}
        persistentVolumeClaim:
          claimName: {{.Values.storage.pvcName}}
      restartPolicy: Never
