# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: o3web-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{.Values.o3web.deployReplicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: o3web-pod
  template:
    metadata:
      name: o3web-template
      labels:
        name: o3web-pod
    spec:
      securityContext:
        runAsUser: {{.Values.security.runAsUser}}
        runAsGroup: {{.Values.security.runAsGroup}}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 20
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: o3web-pod
              topologyKey: kubernetes.io/hostname
      priorityClassName: production-medium
      containers:
      - name: o3web-app
        image: {{.Values.o3web.image}}:{{.Values.o3web.imageTag}}
        imagePullPolicy: {{.Values.o3web.imagePullPolicy}}
        resources:
          requests:
            memory: "1900Mi"
            cpu: "1100m"
          limits:
            memory: "1900Mi"
            cpu: "1100m"
        ports:
        - containerPort: 3000
          name: port0
