apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.storage.pvcName}}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
spec:
  accessModes:
    - {{.Values.storage.pvcAccessMode}}
  storageClassName: {{.Values.storage.pvcStorageClassName}}
  resources:
    requests:
      storage: {{.Values.storage.pvcStorage}}
  volumeName: {{.Values.storage.pvName}}
